CREATE TABLE IF NOT EXISTS TB_CUSTOMER (
	ID bigserial NOT NULL,
	NAME varchar(100) NOT NULL,
	EXCLUSIVE_PLAN bool DEFAULT false,
	AMOUNT numeric(19,4) NOT NULL,
	ACCOUNT_NUMBER varchar(50) NOT NULL,
	BORN_DATE date NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
	UPDATED_DATE TIMESTAMP NOT NULL,
	CONSTRAINT tb_customer_pkey PRIMARY KEY (ID, ACCOUNT_NUMBER, NAME)
);

CREATE TABLE IF NOT EXISTS TB_TRANSACTION (
	ID bigserial NOT NULL PRIMARY KEY,
	AMOUNT numeric(19,2) NOT NULL,
	NAME varchar(100) NOT NULL,
	TRANSACTION_TYPE varchar(50) NOT NULL,
	ACCOUNT_NUMBER varchar(50) NOT NULL,
	TRANSACTION_DATE DATE NOT NULL,
	CREATED_DATE TIMESTAMP NOT NULL,
    UPDATED_DATE TIMESTAMP NOT NULL
);

INSERT INTO TB_CUSTOMER (ID, NAME, EXCLUSIVE_PLAN, AMOUNT, ACCOUNT_NUMBER, BORN_DATE, CREATED_DATE, UPDATED_DATE) VALUES (100, 'MARCELO ALVES', TRUE, 200.00, '000009', '1990-05-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_CUSTOMER (ID, NAME, EXCLUSIVE_PLAN, AMOUNT, ACCOUNT_NUMBER, BORN_DATE, CREATED_DATE, UPDATED_DATE) VALUES (200, 'ADRIANA ALVES', FALSE, 300.00, '000009', '1990-05-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_CUSTOMER (ID, NAME, EXCLUSIVE_PLAN, AMOUNT, ACCOUNT_NUMBER, BORN_DATE, CREATED_DATE, UPDATED_DATE) VALUES (300, 'ALBERTO ALVES', FALSE, 50.00, '000009', '1990-05-05', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO TB_TRANSACTION (ID, AMOUNT, NAME, TRANSACTION_TYPE, ACCOUNT_NUMBER, TRANSACTION_DATE, CREATED_DATE, UPDATED_DATE) VALUES (200, 100.00, 'MARCELO ALVES', 'DEPOSIT', '000009', '2023-05-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_TRANSACTION (ID, AMOUNT, NAME, TRANSACTION_TYPE, ACCOUNT_NUMBER, TRANSACTION_DATE, CREATED_DATE, UPDATED_DATE) VALUES (201, 100.00, 'MARCELO ALVES', 'DEPOSIT', '000009', '2023-05-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_TRANSACTION (ID, AMOUNT, NAME, TRANSACTION_TYPE, ACCOUNT_NUMBER, TRANSACTION_DATE, CREATED_DATE, UPDATED_DATE) VALUES (202, 100.00, 'MARCELO ALVES', 'DEPOSIT', '000009', '2023-05-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
INSERT INTO TB_TRANSACTION (ID, AMOUNT, NAME, TRANSACTION_TYPE, ACCOUNT_NUMBER, TRANSACTION_DATE, CREATED_DATE, UPDATED_DATE) VALUES (203, 100.00, 'MARCELO ALVES', 'DEPOSIT', '000009', '2023-05-10', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
